enum types {
	TOGGLE_FOLLOWED = "TOGGLE_FOLLOWED",
	SET_LOCALE = "SET_LOCALE",
	TOGGLE_SHOW_BOSS_IMAGE = "TOGGLE_SHOW_BOSS_IMAGE",
	TOGGLE_SHOW_USER_IMAGE = "TOGGLE_SHOW_USER_IMAGE",
	SET_TIME_FORMATION = "SET_TIME_FORMATION"
}

export default types
